# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=20)),
                ('SN', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
                ('lastUpdateTime', models.CharField(max_length=20)),
                ('alarm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=20)),
                ('userEmail', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='deviceform',
            name='users',
            field=models.ManyToManyField(null=True, to='PyWebApp.UserForm'),
        ),
    ]
