# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='name',
            new_name='userName',
        ),
    ]
