# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyWebApp', '0002_auto_20161223_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=20)),
                ('SN', models.CharField(max_length=20)),
                ('tempreture', models.CharField(max_length=20)),
                ('lastUpdateTime', models.CharField(max_length=20)),
                ('alarm', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userform',
            name='userPassword',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
