# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyWebApp', '0002_auto_20161231_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceform',
            name='history',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
