# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyWebApp', '0003_auto_20161223_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='devices',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PyWebApp.deviceList'),
            preserve_default=False,
        ),
    ]
